;;; theme-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from modus-operandi-deuteranopia-theme.el

(modus-themes-theme 'modus-operandi-deuteranopia 'modus-themes "\
Deuteranopia-optimized theme with a white background.
This variant is optimized for users with red-green color
deficiency (deuteranopia).  It conforms with the highest
legibility standard for color contrast between background and
foreground in any given piece of text, which corresponds to a
minimum contrast in relative luminance of 7:1 (WCAG AAA
standard)." 'light 'modus-themes-operandi-deuteranopia-palette 'modus-operandi-deuteranopia-palette-user 'modus-operandi-deuteranopia-palette-overrides 'modus-themes-faces-deuteranopia)


;;; Generated autoloads from modus-operandi-theme.el

(modus-themes-theme 'modus-operandi 'modus-themes "\
Elegant, highly legible theme with a white background.
Conforms with the highest legibility standard for color contrast
between background and foreground in any given piece of text,
which corresponds to a minimum contrast in relative luminance of
7:1 (WCAG AAA standard)." 'light 'modus-themes-operandi-palette 'modus-operandi-palette-user 'modus-operandi-palette-overrides)


;;; Generated autoloads from modus-operandi-tinted-theme.el

(modus-themes-theme 'modus-operandi-tinted 'modus-themes "\
Elegant, highly legible theme with a light ochre background.
Conforms with the highest legibility standard for color contrast
between background and foreground in any given piece of text,
which corresponds to a minimum contrast in relative luminance of
7:1 (WCAG AAA standard)." 'light 'modus-themes-operandi-tinted-palette 'modus-operandi-tinted-palette-user 'modus-operandi-tinted-palette-overrides)


;;; Generated autoloads from modus-operandi-tritanopia-theme.el

(modus-themes-theme 'modus-operandi-tritanopia 'modus-themes "\
Tritanopia-optimized theme with a white background.
This variant is optimized for users with blue-yellow color
deficiency (tritanopia).  It conforms with the highest
legibility standard for color contrast between background and
foreground in any given piece of text, which corresponds to a
minimum contrast in relative luminance of 7:1 (WCAG AAA
standard)." 'light 'modus-themes-operandi-tritanopia-palette 'modus-operandi-tritanopia-palette-user 'modus-operandi-tritanopia-palette-overrides 'modus-themes-faces-tritanopia)


;;; Generated autoloads from modus-vivendi-deuteranopia-theme.el

(modus-themes-theme 'modus-vivendi-deuteranopia 'modus-themes "\
Deuteranopia-optimized theme with a black background.
This variant is optimized for users with red-green color
deficiency (deuteranopia).  It conforms with the highest
legibility standard for color contrast between background and
foreground in any given piece of text, which corresponds to a
minimum contrast in relative luminance of 7:1 (WCAG AAA
standard)." 'dark 'modus-themes-vivendi-deuteranopia-palette 'modus-vivendi-deuteranopia-palette-user 'modus-vivendi-deuteranopia-palette-overrides 'modus-themes-faces-deuteranopia)


;;; Generated autoloads from modus-vivendi-theme.el

(modus-themes-theme 'modus-vivendi 'modus-themes "\
Elegant, highly legible theme with a black background.
Conforms with the highest legibility standard for color contrast
between background and foreground in any given piece of text,
which corresponds to a minimum contrast in relative luminance of
7:1 (WCAG AAA standard)." 'dark 'modus-themes-vivendi-palette 'modus-vivendi-palette-user 'modus-vivendi-palette-overrides)


;;; Generated autoloads from modus-vivendi-tinted-theme.el

(modus-themes-theme 'modus-vivendi-tinted 'modus-themes "\
Elegant, highly legible theme with a night sky background.
Conforms with the highest legibility standard for color contrast
between background and foreground in any given piece of text,
which corresponds to a minimum contrast in relative luminance of
7:1 (WCAG AAA standard)." 'dark 'modus-themes-vivendi-tinted-palette 'modus-vivendi-tinted-palette-user 'modus-vivendi-tinted-palette-overrides)


;;; Generated autoloads from modus-vivendi-tritanopia-theme.el

(modus-themes-theme 'modus-vivendi-tritanopia 'modus-themes "\
Tritanopia-optimized theme with a black background.
This variant is optimized for users with blue-yellow color
deficiency (tritanopia).  It conforms with the highest
legibility standard for color contrast between background and
foreground in any given piece of text, which corresponds to a
minimum contrast in relative luminance of 7:1 (WCAG AAA
standard)." 'dark 'modus-themes-vivendi-tritanopia-palette 'modus-vivendi-tritanopia-palette-user 'modus-vivendi-tritanopia-palette-overrides 'modus-themes-faces-tritanopia)

;;; End of scraped data

(provide 'theme-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; theme-loaddefs.el ends here
