;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        my-tab
        qe-forward-kill
        qe-forward-word-end
        ))

(setq mc/cmds-to-run-once
      '(
        ))
