;;; bm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bm.el

(autoload 'bm-toggle "bm" "\
Toggle bookmark at point." t)
(autoload 'bm-toggle-mouse "bm" "\
Toggle a bookmark with a mouse click.
EV is the mouse event.

(fn EV)" t)
(autoload 'bm-lifo-previous "bm" "\
Goto previous bookmark in LIFO order . (that is, most
recently set ones come first, oldest ones come last)" t)
(autoload 'bm-lifo-next "bm" "\
Goto next bookmark in LIFO order .(that is, most
recently set ones come first, oldest ones come last)" t)
(autoload 'bm-next "bm" nil t)
(autoload 'bm-common-next "bm" "\
Goto next bookmark." t)
(autoload 'bm-next-mouse "bm" "\
Go to the next bookmark with the scroll wheel.
EV is the mouse event.

(fn EV)" t)
(autoload 'bm-previous "bm" nil t)
(autoload 'bm-common-previous "bm" "\
Goto previous bookmark." t)
(autoload 'bm-previous-mouse "bm" "\
Go to the previous bookmark with the scroll wheel.
EV is the mouse event.

(fn EV)" t)
(autoload 'bm-remove-all-all-buffers "bm" "\
Delete all visible bookmarks in all open buffers." t)
(autoload 'bm-remove-all-current-buffer "bm" "\
Delete all visible bookmarks in current buffer." t)
(autoload 'bm-bookmark-regexp "bm" "\
Set bookmark on lines that match regexp." t)
(autoload 'bm-show-all "bm" "\
Show bookmarked lines in all buffers." t)
(autoload 'bm-show "bm" "\
Show bookmarked lines in current buffer." t)
(register-definition-prefixes "bm" '("bm-"))


;;; Generated autoloads from bm-sync.el

(register-definition-prefixes "bm-sync" '("bm-bookmark-"))

;;; End of scraped data

(provide 'bm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bm-autoloads.el ends here
