(deftheme my-dark
  "Terminal with dark background.")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'my-dark

   `(ace-jump-face-foreground ((,class (:foreground "#FFFFFF" :background "#0087AF"))))
   `(bm-face ((,class (:foreground nil :background "#5F005F"))))
   `(compilation-mode-line-exit ((,class (:background nil :foreground "#00CD00"))))
   `(compilation-mode-line-fail ((,class (:background nil :foreground "#FF0000"))))
   `(font-lock-builtin-face ((,class (:foreground "#D7AF87"))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#808080"))))
   `(font-lock-comment-face ((,class (:foreground "#808080"))))
   `(font-lock-constant-face ((,class (:foreground "#AFD75F"))))
   `(font-lock-doc-face ((,class (:foreground "#AF8787"))))
   `(font-lock-doc-string-face ((,class (:foreground "#AF8787"))))
   `(font-lock-function-name-face ((,class (:foreground "#D7AF00"))))
   `(font-lock-keyword-face ((,class (:foreground "#00AFFF"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#FFD700"))))
   `(font-lock-reference-face ((,class (:foreground "#FF8787"))))
   `(font-lock-regexp-grouping-backslash ((,class (:weight bold))))
   `(font-lock-regexp-grouping-construct ((,class (:weight bold))))
   `(font-lock-string-face ((,class (:foreground "#D75FAF"))))
   `(font-lock-type-face ((,class (:foreground "#87FFFF"))))
   `(font-lock-variable-name-face ((,class (:foreground "#5FFF87"))))
   `(font-lock-warning-face ((,class (:foreground "#CD0000"))))
   `(header-line ((,class (:underline nil :foreground "#E4E4E4" :background "#303030"))))
   `(highlight ((,class (:background "#444444" :foreground nil))))
   `(ido-first-match ((,class (:weight normal :foreground "#CDCD00"))))
   `(ido-only-match ((,class (:weight normal :foreground "#00FF00"))))
   `(ido-subdir ((,class (:foreground nil :inherit font-lock-keyword-face))))
   `(isearch ((,class (:background "#D75F5F" :foreground "#FFFFFF"))))
   `(isearch-lazy-highlight-face ((,class (:background "#875F00" :foreground "#FFFFFF"))))
   `(my-tab-face ((,class (:background "#D787AF"))))
   `(region ((,class (:background "#005FAF"))))
   `(show-mark-face ((,class (:background "#5F5F5F"))))
   `(show-mark-face-eol ((,class (:underline t :foreground "#5F5F5F"))))
   `(show-paren-match-face ((,class (:background "#005FFF" :foreground "#FFFFFF"))))
   `(show-paren-mismatch-face ((,class (:background "#AF0000" :foreground "#FFFFFF"))))
   `(trailing-whitespace ((,class (:background "#005F87"))))

   ))

(provide-theme 'my-dark)
