(deftheme my-misterioso
  "Terminal with light background.")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'my-misterioso

   `(font-lock-builtin-face           ((,class (:foreground "color-44"))))
   `(font-lock-comment-delimiter-face ((,class (:inherit font-lock-comment-face))))
   `(font-lock-comment-face           ((,class (:foreground "color-102" :slant italic))))
   `(font-lock-constant-face          ((,class (:foreground "color-72"))))
   `(font-lock-function-name-face     ((,class (:foreground "color-50"))))
   `(font-lock-keyword-face           ((,class (:foreground "color-214" :weight bold))))
   `(font-lock-string-face            ((,class (:foreground "color-166"))))
   `(font-lock-type-face              ((,class (:foreground "color-80"))))
   `(font-lock-variable-name-face     ((,class (:foreground "color-186"))))
   `(font-lock-warning-face           ((,class (:foreground "color-203" :weight bold))))
   `(header-line                      ((,class (:foreground "color-236" :background "white"))))
   `(highlight                        ((,class (:foreground "color-254" :background "color-66"))))
   `(isearch                          ((,class (:foreground "black" :background "color-229"))))
   `(lazy-highlight                   ((,class (:background "color-66"))))
   `(link                             ((,class (:foreground "color-81" :underline t))))
   `(link-visited                     ((,class (:foreground "color-212" :underline t))))
   `(minibuffer-prompt                ((,class (:foreground "color-74"))))
   `(mode-line                        ((,class (:foreground "color-255" :background "color-24"))))
   `(mode-line-buffer-id              ((,class (:foreground "yellow" :weight bold))))
   `(mode-line-inactive               ((,class (:foreground "color-255" :background "color-102"))))
   `(region                           ((,class (:foreground "color-254" :background "color-23"))))
   `(show-paren-match-face            ((,class (:foreground "color-46" :background "color-238" :weight bold))))
   `(show-paren-mismatch-face         ((,class (:foreground "color-160" :background "color-238" :weight bold))))
   `(trailing-whitespace              ((,class (:background "color-203"))))
   `(show-mark-face                   ((,class (:foreground nil :background "color-58"))))
   `(avy-lead-face                    ((,class (:foreground "white" :background "color-161" :slant normal :weight bold))))
   `(avy-lead-face-0                  ((,class (:foreground "white" :background "color-25" :slant normal :weight bold))))
   `(avy-lead-face-1                  ((,class (:foreground "white" :background "gray" :slant normal :weight bold))))
   `(avy-lead-face-2                  ((,class (:foreground "white" :background "color-207" :slant normal :weight bold))))
   `(font-lock-doc-face               ((,class (:foreground "color-137"))))
   `(font-lock-doc-string-face        ((,class (:inherit font-lock-doc-face))))
   `(font-lock-preprocessor-face      ((,class (:foreground "color-178"))))
   `(font-lock-reference-face         ((,class (:foreground "color-216"))))
   `(error                            ((,class (:inherit font-lock-warning-face))))

   `(ido-first-match                  ((,class (:foreground "color-227" :background nil))))
   `(ido-only-match                   ((,class (:foreground "color-41" :background nil))))
   `(ido-subdir                       ((,class (:inherit font-lock-keyword-face))))

;;    `(isearch                                 ((,class (:foreground "color-15" :background "color-202"))))
;;    `(isearch-fail                            ((,class (:foreground "color-15" :background "red"))))
;;    `(isearch-lazy-highlight-face             ((,class (:foreground "black" :background "color-181"))))
;;    `(lazy-highlight-face                     ((,class (:foreground "black" :background "color-181"))))

;;    `(bm-face                                 ((,class (:foreground nil :background "color-227"))))
;;    `(button                                  ((,class (:foreground "color-30"))))
;;    `(compilation-column-number               ((,class (:foreground "color-55"))))
;;    `(compilation-error                       ((,class (:foreground "red" :weight bold))))
;;    `(compilation-info                        ((,class (:foreground "color-28"))))
;;    `(compilation-line-number                 ((,class (:foreground "color-18"))))
;;    `(compilation-mode-line-exit              ((,class (:foreground "color-15" :background "green"))))
;;    `(compilation-mode-line-fail              ((,class (:foreground "color-15" :background "red"))))
;;    `(compilation-mode-line-run               ((,class (:foreground "black" :background "color-152"))))
;;    `(cperl-array-face                        ((,class (:foreground "color-62" :background nil))))
;;    `(cperl-hash-face                         ((,class (:foreground "cyan" :background nil))))
;;    `(cperl-nonoverridable-face               ((,class (:foreground "color-94"))))
;;    `(custom-group-tag                        ((,class (:foreground "color-75"))))
;;    `(custom-variable-tag                     ((,class (:foreground "color-75"))))
;;    `(diff-added                              ((,class (:foreground "green" :background nil))))
;;    `(diff-changed                            ((,class (:foreground "color-21" :background nil))))
;;    `(diff-refine-added                       ((,class (:foreground "color-22" :background "color-194"))))
;;    `(diff-refine-change                      ((,class (:foreground "color-18" :background "color-153"))))
;;    `(diff-refine-removed                     ((,class (:foreground "color-160" :background "color-224"))))
;;    `(diff-removed                            ((,class (:foreground "red" :background nil))))
;;    `(dired-marked                            ((,class (:foreground "color-15" :background "color-32"))))
;;    `(ediff-current-diff-A                    ((,class (:foreground "black" :background "color-179"))))
;;    `(ediff-current-diff-B                    ((,class (:foreground "black" :background "color-152"))))
;;    `(ediff-even-diff-A                       ((,class (:foreground "black" :background "color-254"))))
;;    `(ediff-even-diff-B                       ((,class (:foreground "black" :background "color-254"))))
;;    `(ediff-fine-diff-A                       ((,class (:background "color-221"))))
;;    `(ediff-fine-diff-B                       ((,class (:background "color-81"))))
;;    `(ediff-odd-diff-A                        ((,class (:foreground "black" :background "color-251"))))
;;    `(ediff-odd-diff-B                        ((,class (:foreground "black" :background "color-251"))))
;;    `(escape-glyph                            ((,class (:foreground "color-124" :background "color-230"))))
;;    `(etags-select-highlight-tag-face         ((,class (:foreground "color-254" :background "color-25"))))
;;    `(flymake-errline                         ((,class (:background "color-224" :inherit nil))))
;;    `(flymake-warnline                        ((,class (:background "color-230" :inherit nil ))))
;;    `(header-line                             ((,class (:foreground "color-254" :background "color-236" :underline nil))))
;;    `(hi-blue                                 ((,class (:foreground "black" :background "color-117"))))
;;    `(hi-green                                ((,class (:foreground "black" :background "color-120"))))
;;    `(hi-pink                                 ((,class (:foreground "black" :background "color-218"))))
;;    `(hi-yellow                               ((,class (:foreground "black" :background "color-220"))))
;;    `(highlight                               ((,class (:foreground "black" :background "color-117"))))
;;    `(hl-line                                 ((,class (:background "color-230" :inherit nil))))
;;    `(info-header-node                        ((,class (:foreground "green"))))
;;    `(info-header-xref                        ((,class (:foreground "color-39" :inherit info-xref))))
;;    `(info-menu-star                          ((,class (:foreground "black"))))
;;    `(info-node                               ((,class (:foreground "color-39"))))
;;    `(info-title-1                            ((,class (:foreground "color-100"))))
;;    `(info-title-2                            ((,class (:foreground "color-106"))))
;;    `(info-xref                               ((,class (:foreground "color-12" :inherit link))))
;;    `(link                                    ((,class (:foreground "color-20"))))
;;    `(link-visited                            ((,class (:foreground "color-13" :inherit link))))
;;    `(magit-blame-heading                     ((,class (:background "color-253"))))
;;    `(magit-branch-local                      ((,class (:foreground "color-74"))))
;;    `(magit-branch-remote                     ((,class (:foreground "color-65"))))
;;    `(magit-diff-added                        ((,class (:inherit diff-added))))
;;    `(magit-diff-added-highlight              ((,class (:inherit diff-refine-added))))
;;    `(magit-diff-base                         ((,class (:inherit diff-changed))))
;;    `(magit-diff-base-highlight               ((,class (:inherit diff-refine-change))))
;;    `(magit-diff-conflict-heading             ((,class (:inherit error))))
;;    `(magit-diff-context                      ((,class :inherit font-lock-comment-face)))
;;    `(magit-diff-context-highlight            ((,class (:foreground "color-240" :background "color-253"))))
;;    `(magit-diff-file-heading-highlight       ((,class (:inherit diff-file-header))))
;;    `(magit-diff-file-heading-selection       ((,class (:foreground "color-216" :inherit diff-file-header))))
;;    `(magit-diff-removed                      ((,class (:inherit diff-removed))))
;;    `(magit-diff-removed-highlight            ((,class (:inherit diff-refine-removed))))
;;    `(magit-log-date                          ((,class (:inherit font-lock-comment-face))))
;;    `(magit-log-graph                         ((,class (:inherit font-lock-comment-face))))
;;    `(magit-refname                           ((,class (:inherit font-lock-comment-face))))
;;    `(magit-section-heading                   ((,class (:foreground "color-172"))))
;;    `(magit-section-highlight                 ((,class (:background "color-254"))))
;;    `(magit-sequence-head                     ((,class (:foreground "color-110"))))
;;    `(magit-sequence-part                     ((,class (:foreground "color-172"))))
;;    `(magit-sequence-stop                     ((,class (:foreground "color-65"))))
;;    `(magit-tag                               ((,class (:foreground "color-172"))))
;;    `(match                                   ((,class (:background "color-223"))))
;;    `(minibuffer-prompt                       ((,class (:foreground "color-24"))))
;;    `(mode-line                               ((,class (:foreground "black" :background "color-250"))))
;;    `(mode-line-buffer-id                     ((,class (:foreground "color-20"))))
;;    `(mode-line-inactive                      ((,class (:foreground "color-250" :background "color-255"))))
;;    `(my-debug-face                           ((,class (:foreground "black" :background "color-208"))))
;;    `(my-fixme-face                           ((,class (:foreground "color-15" :background "red"))))
;;    `(my-ibuffer-current-face                 ((,class (:foreground "color-165" :background nil))))
;;    `(my-modified-face                        ((,class (:foreground "color-254" :background "color-124"))))
;;    `(my-narrow-face                          ((,class (:foreground "black" :background "color-11"))))
;;    `(my-read-only-face                       ((,class (:foreground "black" :background "color-208"))))
;;    `(my-tab-face                             ((,class (:background "color-224"))))
;;    `(my-todo-face                            ((,class (:foreground "black" :background "color-11"))))
;;    `(org-checkbox-statistics-done            ((,class (:foreground "color-28"))))
;;    `(org-checkbox-statistics-todo            ((,class (:foreground "color-95"))))
;;    `(org-date                                ((,class (:foreground "color-24"))))
;;    `(org-document-title                      ((,class (:foreground "color-100"))))
;;    `(org-special-keyword                     ((,class (:foreground "color-94"))))
;;    `(org-tag                                 ((,class (:foreground "color-69"))))
;;    `(org-todo                                ((,class (:foreground "color-95"))))
;;    `(outline-1                               ((,class (:inherit font-lock-function-name-face))))
;;    `(outline-2                               ((,class (:foreground "color-33"))))
;;    `(outline-3                               ((,class (:foreground "color-67"))))
;;    `(outline-4                               ((,class (:foreground "color-62"))))
;;    `(outline-5                               ((,class (:foreground "color-39"))))
;;    `(primary-selection                       ((,class (:background "color-20"))))
;;    `(region                                  ((,class (:background "color-153"))))
;;    `(sh-heredoc                              ((,class (:foreground "color-136"))))
;;    `(sh-quoted-exec                          ((,class (:foreground "color-141"))))
;;    `(sqlplus-table-head-face                 ((,class (:foreground "color-254" :background "color-236" :underline nil))))
;;    `(sqlplus-table-odd-rows-face             ((,class (:background "color-252"))))
;;    `(trailing-whitespace                     ((,class (:background "color-195"))))
;;    `(vertical-border                         ((,class (:foreground "color-248"))))
;;    `(warning                                 ((,class (:foreground "color-100" :weight bold))))
;;    `(web-mode-current-element-highlight-face ((,class (:background "color-193"))))
;;    `(web-mode-html-attr-name-face            ((,class (:foreground "color-109"))))

   ))

(provide-theme 'my-misterioso)
