(deftheme smf-base-light
  "Base light colors.")

(customize-set-variable 'frame-background-mode 'light)
(load-theme 'smf-base t)

(custom-theme-set-faces
 'smf-base-light

 `(bm-face                             ((t :foreground "black" :background ,(smf-color 221))))
 `(caution                             ((t :foreground "black" :background ,(smf-color 215))))
 `(cursor                              ((t :background "deeppink2")))
 `(diff-refine-added                   ((t :foreground "black" :background ,(smf-color 157))))
 `(diff-refine-removed                 ((t :foreground "black" :background ,(smf-color 217))))
 `(dired-marked                        ((t :background "lightgoldenrodyellow")))
 `(dired-subtree-depth-1-face          ((t :background "snow")))
 `(dired-subtree-depth-2-face          ((t :background "ghostwhite")))
 `(dired-subtree-depth-3-face          ((t :background "whitesmoke")))
 `(dired-subtree-depth-4-face          ((t :background "floralwhite")))
 `(dired-subtree-depth-5-face          ((t :background "oldlace")))
 `(dired-subtree-depth-6-face          ((t :background "linen")))
 `(easy-escape-delimiter-face          ((t :foreground "green4" :background "gray95")))
 `(ediff-current-diff-A                ((t :foreground "black" :background ,(smf-color 153))))
 `(ediff-even-diff-A                   ((t :foreground "black" :background ,(smf-color 253))))
 `(ediff-fine-diff-A                   ((t :foreground "black" :background ,(smf-color 215))))
 `(ediff-odd-diff-A                    ((t :foreground "black" :background ,(smf-color 253))))
 `(error                               ((t :foreground ,(smf-color 231) :background ,(smf-color 124))))
 `(flymake-error                       ((t :background "mistyrose")))
 `(flymake-note                        ((t :background "thistle1")))
 `(flymake-warning                     ((t :background "lightyellow")))
 `(font-lock-regexp-grouping-construct ((t :background "whitesmoke" :bold t)))
 `(header-line                         ((t :foreground ,(smf-color 252) :background ,(smf-color 238))))
 `(isearch                             ((t :background "coral2" :foreground ,(smf-color 231))))
 `(lazy-highlight                      ((t :background "cornsilk" :foreground "black")))
 `(line-number                         ((t :foreground ,(smf-color 17) :background ,(smf-color 253) :italic t)))
 `(line-number-current-line            ((t :inherit line-number :inverse-video t)))
 `(link                                ((t :foreground ,(smf-color 26) :italic t :underline t)))
 `(link-visited                        ((t :foreground ,(smf-color 93) :italic t :underline t)))
 `(markdown-code-face                  ((t :background "gray97")))
 `(markdown-table-face                 ((t :foreground "steelblue4")))
 `(match                               ((t :inherit ediff-fine-diff-A)))
 `(mc/cursor-face                      ((t :foreground "white" :background ,(smf-color 162))))
 `(my-display-table-face               ((t :foreground ,(smf-color 17) :background ,(smf-color 253) :bold t)))
 `(org-block-background                ((t :background "ivory")))
 `(org-code                            ((t :inherit org-block-background :bold t)))
 `(outline-1                           ((t :foreground ,(smf-color 26) :bold t)))
 `(outline-2                           ((t :foreground ,(smf-color 32) :bold t)))
 `(outline-3                           ((t :foreground "cyan4" :bold t)))
 `(outline-4                           ((t :foreground ,(smf-color 130) :bold t)))
 `(p4o-merge-face                      ((t :background "lightyellow")))
 `(rg-literal-face                     ((t :foreground "lightblue")))
 `(rg-regexp-face                      ((t :foreground "yellow")))
 `(show-mark-face                      ((t :foreground "black" :background ,(smf-color 195))))
 `(speedbar-button-face                ((t :foreground "black")))
 `(sqlplus-table-odd-rows-face         ((t :background ,(smf-color 254))))
 `(success                             ((t :foreground "black" :background ,(smf-color 157))))
 `(trailing-whitespace                 ((t :background ,(smf-color 255))))
 `(warning                             ((t :foreground "black" :background ,(smf-color 227))))
 `(web-mode-html-attr-custom-face      ((t :foreground ,(smf-color 143))))
 `(web-mode-html-attr-name-face        ((t :foreground ,(smf-color 65))))
 `(web-mode-html-attr-value-face       ((t :foreground ,(smf-color 138))))
 `(web-mode-html-tag-face              ((t :foreground ,(smf-color 67))))

 )

(provide-theme 'smf-base-light)
