(deftheme smf-base-dark
  "Base dark colors.")

(customize-set-variable 'frame-background-mode 'dark)
(load-theme 'smf-base t)

(custom-theme-set-faces
 'smf-base-dark

 `(bm-face                        ((t :foreground "white" :background "dodgerblue4")))
 `(caution                        ((t :foreground "white" :background "darkorange3")))
 `(cursor                         ((t :background "deeppink2")))
 `(diff-refine-added              ((t :inherit success)))
 `(diff-refine-removed            ((t :inherit error)))
 `(easy-escape-delimiter-face     ((t :foreground "green" :background "gray25")))
 `(ediff-current-diff-A           ((t :background ,(smf-color 53))))
 `(ediff-even-diff-A              ((t :background ,(smf-color 237))))
 `(ediff-fine-diff-A              ((t :foreground ,(smf-color 255) :background ,(smf-color 22))))
 `(ediff-odd-diff-A               ((t :background ,(smf-color 237))))
 `(error                          ((t :foreground "white" :background "red4")))
 `(flymake-error                  ((t :background "firebrick4")))
 `(flymake-warning                ((t :background "yellow4")))
 `(header-line                    ((t :foreground ,(smf-color 255) :background "black")))
 `(isearch                        ((t :foreground ,(smf-color 231) :background ,(smf-color 203))))
 `(lazy-highlight                 ((t :foreground ,(smf-color 231) :background ,(smf-color 66))))
 `(link                           ((t :foreground ,(smf-color 81) :italic t :underline t)))
 `(link-visited                   ((t :foreground ,(smf-color 212) :italic t :underline t)))
 `(line-number                    ((t :foreground "wheat3" :background "black" :italic t)))
 `(line-number-current-line       ((t :inherit line-number :inverse-video t)))
 `(match                          ((t :foreground ,(smf-color 231) :background ,(smf-color 62))))
 `(mc/cursor-face                 ((t :foreground "white" :background ,(smf-color 162))))
 `(org-block-background           ((t :background "ivory")))
 `(org-code                       ((t :inherit org-block-background :bold t)))
 `(outline-1                      ((t :foreground ,(smf-color 45))))
 `(outline-2                      ((t :foreground ,(smf-color 44))))
 `(outline-3                      ((t :foreground ,(smf-color 43))))
 `(outline-4                      ((t :foreground ,(smf-color 42))))
 `(p4o-merge-face                 ((t :inherit warning)))
 `(show-mark-face                 ((t :foreground nil :background ,(smf-color 239))))
 `(speedbar-button-face           ((t :foreground "white")))
 `(sqlplus-table-odd-rows-face    ((t :background ,(smf-color 254))))
 `(success                        ((t :foreground "white" :background "darkgreen")))
 `(trailing-whitespace            ((t :background ,(smf-color 52))))
 `(warning                        ((t :foreground "black" :background "yellow3")))
 `(web-mode-html-attr-custom-face ((t :foreground ,(smf-color 106))))
 `(web-mode-html-attr-name-face   ((t :foreground ,(smf-color 108))))
 `(web-mode-html-attr-value-face  ((t :foreground ,(smf-color 137))))
 `(web-mode-html-tag-face         ((t :foreground ,(smf-color 110))))

 )

(provide-theme 'smf-base-dark)
